package com.hqep.dataSharingPlatform.sjfwgj.pojo;

import java.util.Date;

public class DisposelogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcfw_disposelog.ticket_id
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    private String ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcfw_disposelog.result
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcfw_disposelog.handle_time
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcfw_disposelog.operateTitle
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    private String operatetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcfw_disposelog.node_time
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    private String nodeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcfw_disposelog.ticket_id
     *
     * @return the value of lcfw_disposelog.ticket_id
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcfw_disposelog.ticket_id
     *
     * @param ticketId the value for lcfw_disposelog.ticket_id
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId == null ? null : ticketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcfw_disposelog.result
     *
     * @return the value of lcfw_disposelog.result
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcfw_disposelog.result
     *
     * @param result the value for lcfw_disposelog.result
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcfw_disposelog.handle_time
     *
     * @return the value of lcfw_disposelog.handle_time
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcfw_disposelog.handle_time
     *
     * @param handleTime the value for lcfw_disposelog.handle_time
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcfw_disposelog.operateTitle
     *
     * @return the value of lcfw_disposelog.operateTitle
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public String getOperatetitle() {
        return operatetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcfw_disposelog.operateTitle
     *
     * @param operatetitle the value for lcfw_disposelog.operateTitle
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public void setOperatetitle(String operatetitle) {
        this.operatetitle = operatetitle == null ? null : operatetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcfw_disposelog.node_time
     *
     * @return the value of lcfw_disposelog.node_time
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public String getNodeTime() {
        return nodeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcfw_disposelog.node_time
     *
     * @param nodeTime the value for lcfw_disposelog.node_time
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    public void setNodeTime(String nodeTime) {
        this.nodeTime = nodeTime == null ? null : nodeTime.trim();
    }
}