package com.hqep.dataSharingPlatform.sjfwgj.dao;

import com.hqep.dataSharingPlatform.sjfwgj.pojo.DisposelogDO;
import org.springframework.stereotype.Repository;

@Repository
public interface disposelogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_disposelog
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_disposelog
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    int insert(DisposelogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_disposelog
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    int insertSelective(DisposelogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_disposelog
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    DisposelogDO selectByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_disposelog
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    int updateByPrimaryKeySelective(DisposelogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_disposelog
     *
     * @mbg.generated Tue Apr 25 20:02:12 CST 2023
     */
    int updateByPrimaryKey(DisposelogDO record);
}