package com.hqep.dataSharingPlatform.sjfwgj.dao;

import com.hqep.dataSharingPlatform.sjfwgj.pojo.ReceiveDetailDO;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ReceiveDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_table
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_table
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int insert(ReceiveDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_table
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int insertSelective(ReceiveDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_table
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    ReceiveDetailDO selectByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_table
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int updateByPrimaryKeySelective(ReceiveDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_table
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int updateByPrimaryKey(ReceiveDetailDO record);


    boolean insert(Map map1);

    Map selectdetail();
    List<Map> selectDetaillist();

}