package com.hqep.dataSharingPlatform.sjfwgj.dao;

import com.hqep.dataSharingPlatform.sjfwgj.pojo.ReceiveDO;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ReceiveDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_demand_d_to
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_demand_d_to
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int insert(ReceiveDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_demand_d_to
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int insertSelective(ReceiveDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_demand_d_to
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_demand_d_to
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int updateByPrimaryKeySelective(ReceiveDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcfw_demand_d_to
     *
     * @mbg.generated Mon May 01 19:33:29 CST 2023
     */
    int updateByPrimaryKey(ReceiveDO record);

    boolean insert(Map map1);

    Map select();

    List<Map> selectlist();

}